# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.10.150636'

RELEASE_GIT_HEAD = 'f7d3453e03496b286d65c3c05733256b375b1502'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'SUSA2as2/yt-dlp'

ORIGIN = 'SUSA2as2/yt-dlp'

_pkg_version = '2025.03.10.150636'
