# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.10.144918'

RELEASE_GIT_HEAD = '42ed6b0e1f5e5314edb22fba7694c67d9b8d21a1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'SUSA2as2/yt-dlp'

ORIGIN = 'SUSA2as2/yt-dlp'

_pkg_version = '2025.03.10.144918'
